---
always_tasks: []

pre: True
apt: True
pip: True
gpg: True
git: True
xonsh: True
home: True

cron_dir_root: /root/cron
cron_dir_user: ~/bin/cron

kodi_default:
  dir: '/home/{{ user }}'
  favorites: []
  guisettings:
    lookandfeel.skin: skin.estuary
    services.webserver: 'true'
    services.webserverport: 8080
    services.webserverauthentication: 'true'
    services.webserverusername: '{{ secrets.kodi.api.username | default("") }}'
    services.webserverpassword: '{{ secrets.kodi.api.password | default("") }}'
  linux:
    user: '{{ user }}'
    group: '{{ user }}'
  mediasources: {}
  sources:
    files: []
    games: []
    music:
      - name: Auto-mounted drives
        path: /media/
    pictures: []
    programs: []
    video:
      - name: Auto-mounted drives
        path: /media/

kodi_addons:
  config_dir: .kodi/userdata/addon_data
  db_dir: .kodi/userdata/Database
  db_regex: 'Addons[0-9]+\.db'
  dir: .kodi/addons
  youtube:
    asset:
      default: 'plugin.video.youtube-[0-9.]+.zip'
      19: 'plugin.video.youtube-[0-9.]+\\+matrix.1.zip'
    configure: true
    dl_method: github-release
    name: plugin.video.youtube
    repo: anxdpanic/plugin.video.youtube

kodi_userdata: .kodi/userdata
kodi_favourites: .kodi/userdata/favourites.xml
kodi_guisettings: .kodi/userdata/guisettings.xml
kodi_mediasources: .kodi/userdata/mediasources.xml
kodi_sources: .kodi/userdata/sources.xml
