---
kodi:
  addons:
    youtube: {}
  favorites:
    - name: Josh Music
      window: 10502
      path: smb://trichiliocosm/sibyl/audio/laptopdude/MUSIC/
    - name: Josh Anime
      window: 10025
      path: smb://trichiliocosm/sibyl/video/laptopdude/Anime/Series/
  guisettings:
    audiooutput.channels: 1
  mediasources:
    network:
      - smb://trichiliocosm/sibyl
  sources:
    music:
      - name: trichiliocosm
        path: smb://trichiliocosm/sibyl/audio
    video:
      - name: trichiliocosm
        path: smb://trichiliocosm/sibyl/video/
