colorscheme selenized
set background=dark
set t_Co=16
syntax enable

set modeline
set modelines=2

set colorcolumn=80
set cursorline
set list
set listchars=trail:▚,precedes:◀,extends:▶,tab:┼─
set number
set ruler

set autoindent
set expandtab
set shiftwidth=2
set smartindent
set softtabstop=2
set tabstop=2
