---
- name: Clone git repos
  git:
    repo: '{{ git.url_prefix }}{{ item.key }}/{{ item.value }}{{ git.url_suffix }}'
    dest: ~/src/git/{{ item.value }}
  with_dict: '{{ git.repos }}'
  become: False
