---
- name: Install xonsh
  pip:
    name:
      - xonsh[full]

- name: Get python version
  command:
    cmd: python3 --version
  register: raw_python_version
  changed_when: False

- name: Parse python version
  set_fact:
    python_version: '{{ raw_python_version.stdout | regex_search("[0-9.]+$") }}'

- name: Create xonshrc dir
  file:
    path: ~/.config/xonsh/rc.d
    state: directory
  become: False

- name: Generate ansible .xonshrc
  template:
   src: xonshrc_ansible.j2
   dest: ~/.config/xonsh/rc.d/00_ansible.xsh
   lstrip_blocks: True
  become: False

- name: Create empty user override .xonshrc
  template:
    src: xonshrc_local.j2
    dest: ~/.config/xonsh/rc.d/99_local.xsh
    force: False
    lstrip_blocks: True
  become: False

- name: Symlink user override .xonshrc
  file:
    path: ~/.xrc
    state: link
    src: .config/xonsh/rc.d/99_local.xsh
  become: False

- name: Find xonsh path
  command:
    cmd: which xonsh
  register: xonsh_path
  changed_when: False

- name: Add xonsh to shells
  lineinfile:
    path: /etc/shells
    regexp: '{{ xonsh_path.stdout }}'
    line: '{{ xonsh_path.stdout }}'

- name: Set shell to xonsh
  command:
    cmd: 'chsh -s {{ xonsh_path.stdout }} {{ user }}'
